trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: java -version
  displayName: 'Check Java version'

- script: mvn -version
  displayName: 'Check Maven version'

- script: |
    echo Running tests on LambdaTest...
    mvn test -D suite=single.xml
  displayName: 'Run LambdaTest Suite'


