trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitecture: 'x64'
  displayName: 'Install Java 11'

- script: |
    echo Installing Maven...
    sudo apt-get update
    sudo apt-get install -y maven
  displayName: 'Install Maven'

- script: |
    echo Running tests on LambdaTest...
    mvn test -D suite=single.xml
  displayName: 'Run LambdaTest Suite'
